apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-app
  template:
    metadata:
      labels:
        app: movie-app
    spec:
      containers:
      - name: movie-app
        image: naidu1142/multibranch-flask-app:build-12
        ports:
        - containerPort: 5000
